name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push user service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service1:latest ./service1
          docker push ${{ secrets.DOCKER_USERNAME }}/service1:latest

      - name: Build and push product service Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service2:latest ./service2
          docker push ${{ secrets.DOCKER_USERNAME }}/service2:latest

      - name: Deploy services using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d
